### ISSUE TITLE
Relocate Edit and Delete buttons to left side of Cards Listing page

### ISSUE THREAD

**Issue by timkyoung** [oatear/cider#25]
I'm working on a game with 21 different possible card attributes. Currently when I want to edit a card I have to scroll to the right on the Cards/Listing page to be able to access the edit button, due to the large number of attributes my cards have. It would be nice to be able to access the Edit and Delete buttons without having to use the horizontal scroll bar. This could be achieved by relocating the edit and delete buttons to the left side of the Cards/Listing page.

**Comment by hristoiankov** [comment]
This issue has been addressed with a frozen action column. The table can be scrolled horizontally, but the action column remains visible.
