### ISSUE TITLE
Alert: "Unsaved changes will be lost!"

### ISSUE THREAD

**Issue by timkyoung** [oatear/cider#26]
Failing to save changes to templates before navigating away from the templates page results in unsaved changes being lost. Displaying an alert that reminds the user that unsaved changes will be lost when user attempts to navigate away from the templates page would help prevent losing unsaved changes. (An auto-save feature would mitigate this issue as well, but is likely to be more difficult to implement. So the alert should be fine.)

**Comment by crimsonknave** [comment]
This is a huge pain and creates a huge barrier to new users. I just spent 30 minutes working on something, and it was gone and then I spent another 15 minutes trying to figure out why. Control S didn't do anything and saving from the main menu doesn't save the current template before it writes to disk which is very confusing.

**Comment by hristoiankov** [comment]
Removed the save button in templates and setup a debounce save that triggers 1 second after user stops typing into the editors.
