### ISSUE TITLE
Export stuck on generating card images

### ISSUE THREAD

**Issue by maeligg** [oatear/cider#52]
Hello,

First of all, thanks a lot for making and open sourcing this ! It's a really great tool.
I've been having issues with exporting cards, both in pdf and as invividual images. I'm using the example Cosmic Apple Deck. I'm on OSX and I tried with the latest versions of Chrome and Firefox. There are some console errors that might be relevant to this :
![Screenshot 2023-06-16 at 12 12 13](https://github.com/oatear/cider/assets/9273118/e7e7cfdb-a45c-4dda-ae55-c9fc6c6d7e3e)

**Comment by maeligg** [comment]
FWIW it's working on my Windows machine, so this might be an OSX-specific bug.

**Comment by hristoiankov** [comment]
Can you go to the about page on your browsers and copy the version that shows up there? Also if you know, is it an ARM based Mac, or an Intel Mac? I can try to match those versions and reproduce.

**Comment by hristoiankov** [comment]
Also, let me know if you have any plugins active on your browsers like ad blockers or something that could disable javascript.

**Comment by maeligg** [comment]
I tried again in incognito mode with all my extensions disabled and it worked, so that's probably the source of the bug. Sorry for the wrong alert !

**Comment by maeligg** [comment]
This might be unrelated, maybe I should create a new ticket for it, but I now have this hanging export problem in incognito mode as well, except I don't see any console errors or failed network calls. The example deck still exports fine though, so it might be something broken in my card template but it didn't raise any errors.

**Comment by hristoiankov** [comment]
Also be aware that  a standard letter size paper export by default creates 300 dpi (2550x3300 pixel) images per sheet (front + back). It may look like it the export is stuck, but you may have to give it a bit more time.

**Comment by hristoiankov** [comment]
You can also just download the standalone desktop app and use that. That way you won't have to disable your ad/javascript blockers on your browser. There are some other benefits that come with the desktop version.

**Comment by hristoiankov** [comment]
Closing this unless it is still an issue. There have also been some major improvements to the exports in recent revisions.
