### ISSUE TITLE
possible encoding issue regarding German umlaute (after reloading)

### ISSUE THREAD

**Issue by The413x** [oatear/cider#94]
If you put "umlaute" from the German language eg. ä,ü,ö in to cider everything works fine but if you save the project and than reload the project for example `ü` gets transformed to `Ã¼`. Looks like an encoding issue to me.

**Comment by victoic** [comment]
Same happens with portuguese special character ã, ç, à, á, é, etc.

**Comment by The413x** [comment]
It seems to be a problem with loading, 
I can load the saved files with excel and utf-8 encoding and the "umlaute" are encoded correctly so I guess the problem is that the `.csv` files are not loaded with `utf-8 encoding`

**Comment by hristoiankov** [comment]
Sorry, I've been away from the project for a few weeks. I'll take a look at this import issue tonight.

**Comment by hristoiankov** [comment]
Fixed.
